In [1]:
import numpy as np

array_2d = np.array([[1, 2],
					[2, 3.5],
                    [5, 6.5]])

array_2d

array([[1. , 2. ],
       [2. , 3.5],
       [5. , 6.5]])

In [3]:
# 0 => COLUMN
array_2d.sum(axis=0)

array([ 8., 12.])

In [14]:
array_2d.sum(axis=0), array_2d.max(axis=1)

(array([ 8., 12.]), array([2. , 3.5, 6.5]))

In [17]:
import numpy as np

x = np.array([[1, 2.25],
             [2, 3.25],
             [5, 10]])

y = np.array([1, 0.375])

# z = 10 - [8, a]
print(x.max())
print((x * y).sum(axis=0))
z = x.max() - (x * y).sum(axis=0)
z[0]

10.0
[8.     5.8125]


2.0

## Practice Questions

In [6]:
# Q1
import numpy as np

list(np.arange(4) * 3)* 2

[0, 3, 6, 9, 0, 3, 6, 9]

In [11]:
# Q2
import numpy as np

m = [3, 6, 5, 2, 1]
n = np.arange(m.pop(), m.pop(2))
n

array([1, 2, 3, 4])

In [13]:
# Q3

import numpy as np

x = np.array([0, 1, 2, 3])
y = np.array([1, 2, 1, 2])
z = 3.5 * x + y * (1 - x)

z[2]


6.0

In [22]:
# Q4

"""
5.5
26
WRONG
ANS: 27, 26, 15

18
25
24
10
27
22

20

5.5, 17
26, 15

26, 17
21, 21
15.5, 12

17, 5.5, 10
15, 26, 27
21, 21, 22
WRONG: only reverse second last row!
ANS: 15, 26, 27
"""
array_2d = np.array([[18, 26, 17],
					[25, 15.5, 12],
                    [24, 27, 20],
                    [10, 5.5, 17],
                    [27, 26, 15],
                    [22, 21, 21]])

print(array_2d[3:5][1])
print()
print(array_2d[:, 0])
print()
print(array_2d[2][2])
print()
print(array_2d[3:5, 1:])
print()
print(array_2d[[0, 5, 1], 1:])
print()
print(array_2d[-2, ::-1])


[27. 26. 15.]

[18. 25. 24. 10. 27. 22.]

20.0

[[ 5.5 17. ]
 [26.  15. ]]

[[26.  17. ]
 [21.  21. ]
 [15.5 12. ]]

[15. 26. 27.]


In [19]:
# Q5
# [-5, -4, -3]
print(np.arange(3) - 5)
print()

"""
2, 3, 4
2, 3, 4
2, 3, 4
"""
print(np.ones((3,3)) + np.arange(3))
print()

"""
0
1
2

0, 1, 2

0, 1, 2
1, 2, 3
2, 3, 4
"""
print(np.arange(3).reshape((3, 1)) + np.arange(3))

[-5 -4 -3]

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

[[0 1 2]
 [1 2 3]
 [2 3 4]]
